{"name": "使用无效用户名登录", "status": "passed", "description": "测试使用无效用户名登录", "steps": [{"name": "发送登录请求", "status": "passed", "start": 1742985835906, "stop": 1742985835908}, {"name": "验证登录失败", "status": "passed", "start": 1742985835908, "stop": 1742985835908}], "attachments": [{"name": "stderr", "source": "f1b9e4ca-a55b-4197-b00b-a1e4f42c472a-attachment.txt", "type": "text/plain"}], "start": 1742985835906, "stop": 1742985835908, "uuid": "f480547a-2f19-472c-b92f-4e3206c89ef7", "historyId": "98b10f3205b684d85418cc30d76884bf", "testCaseId": "98b10f3205b684d85418cc30d76884bf", "fullName": "test_cases.api.test_demo_api.TestUserAPI#test_login_with_invalid_username", "labels": [{"name": "epic", "value": "API测试"}, {"name": "story", "value": "登录接口"}, {"name": "feature", "value": "用户管理"}, {"name": "parentSuite", "value": "test_cases.api"}, {"name": "suite", "value": "test_demo_api"}, {"name": "subSuite", "value": "TestUserAPI"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "39379-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.api.test_demo_api"}]}