{"name": "使用无效用户名登录", "status": "passed", "description": "测试使用无效用户名登录", "steps": [{"name": "发送登录请求", "status": "passed", "start": 1742985862802, "stop": 1742985862805}, {"name": "验证登录失败", "status": "passed", "start": 1742985862805, "stop": 1742985862805}], "attachments": [{"name": "stderr", "source": "3eab72c8-9a92-4fac-8093-0963dd22e8d0-attachment.txt", "type": "text/plain"}], "start": 1742985862802, "stop": 1742985862805, "uuid": "e9501f2d-6bc8-4f0f-ad06-2f5ae979db93", "historyId": "98b10f3205b684d85418cc30d76884bf", "testCaseId": "98b10f3205b684d85418cc30d76884bf", "fullName": "test_cases.api.test_demo_api.TestUserAPI#test_login_with_invalid_username", "labels": [{"name": "feature", "value": "用户管理"}, {"name": "story", "value": "登录接口"}, {"name": "epic", "value": "API测试"}, {"name": "parentSuite", "value": "test_cases.api"}, {"name": "suite", "value": "test_demo_api"}, {"name": "subSuite", "value": "TestUserAPI"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "39835-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.api.test_demo_api"}]}